<RESPONSE xmlns="">
  <AuthenticationServer>
    <VALUE>lb-lsg-auth.catalog.ubi.com:3078</VALUE>
  </AuthenticationServer>
  <AuthPS3BaseURL>
    <VALUE>http://ps3webauth.ubi.com/EnterExclusiveContent.aspx</VALUE>
  </AuthPS3BaseURL>
  <GatorAuthServiceActivity>
    <VALUE>UGC_FARCRY2_PS3</VALUE>
  </GatorAuthServiceActivity>
  <GatorAuthServiceHost>
    <VALUE>gatorservice.ubi.com</VALUE>
  </GatorAuthServiceHost>
  <GatorAuthServicePort>
    <VALUE>80</VALUE>
  </GatorAuthServicePort>
  <GatorAuthServiceURI>
    <VALUE
      >http://gconnect.ubi.com:3074/gatorservice/AuthenticationServiceSSL.svc</VALUE
    >
  </GatorAuthServiceURI>
  <GatorConfigServiceURI>
    <VALUE>http://gconnect.ubi.com:3074/gatorservice/ConfigService.svc</VALUE>
  </GatorConfigServiceURI>
  <GatorContentServiceURI>
    <VALUE>http://gconnect.ubi.com:3074/gatorservice/ContentService.svc</VALUE>
  </GatorContentServiceURI>
  <GatorServiceHost>
    <VALUE>gconnect.ubi.com</VALUE>
  </GatorServiceHost>
  <GatorServicePort>
    <VALUE>3074</VALUE>
  </GatorServicePort>
  <GatorTransferServiceURI>
    <VALUE>/TransferService.svc</VALUE>
  </GatorTransferServiceURI>
  <GatorUserServiceURI>
    <VALUE
      >http://secure.catalog.ubi.com/gatorservice/GatorUserService.svc</VALUE
    >
  </GatorUserServiceURI>
  <LobbyServer>
    <VALUE>lb-lsg-mmp.catalog.ubi.com:3036</VALUE>
  </LobbyServer>
  <MmpTitleId>
    <VALUE>0x2786</VALUE>
  </MmpTitleId>
  <NetworkPlatformCommunicationId>
    <VALUE>NPWR00419</VALUE>
  </NetworkPlatformCommunicationId>
  <NetworkPlatformServiceId>
    <VALUE>UP0001-BLUS30178_00</VALUE>
  </NetworkPlatformServiceId>
  <SubContextName>
    <VALUE>FARCRY2_PS3</VALUE>
  </SubContextName>
  <UmProductID>
    <VALUE>PL-FC_F-FC3_SF-FC3PS3</VALUE>
  </UmProductID>
  <UmSonyServiceId>
    <VALUE>UP0001-BLUS30178_00</VALUE>
  </UmSonyServiceId>
  <UmTypeID>
    <VALUE>GAME</VALUE>
  </UmTypeID>
</RESPONSE>
